version: "3"

networks:
  geo_api:
    driver: bridge

services:
  server:
    build:
      context: ./server
    working_dir: /app
    volumes:
      - ./server:/app/
      - /app/node_modules
    ports:
      - "8088:8080"
    networks:
      - geo_api
